### ISSUE TITLE
что это в css?

### ISSUE THREAD

**Issue by Lyumih** [Aruytehno/aruytehno.github.io#5]
Что означает плюсы в css? почему не минус?
```css
        form {
            margin: 0 auto;
            margin-top: +20%;
        }
        h2 {
            font-family: Verdana, Arial, Helvetica, sans-serif;
            margin-bottom: +3%;
        }
```
